# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: glafitte <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/09/11 09:05:57 by glafitte          #+#    #+#              #
#    Updated: 2014/09/11 12:18:17 by glafitte         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

SRC = ft_cat.c

all:
	gcc -c -Wall -Wextra -Werror $(SRC)
	gcc -o $(NAME) ft_cat.o

clean:
	rm -f ft_cat.o

fclean: clean
	rm -f $(NAME)
